### ISSUE TITLE
Pomylona kolejność logów na serwerze (OC)

### ISSUE THREAD

**Issue by bacza** [bacza/geocentral-lite#55]
Zgłoszenie testera:
> Program tak spieszy się z logowaniem, że w efekcie myli się kolejność wpisów na serwerze
> i tak log późniejszy ląduje wcześniej na liście - na szczęście z poprawnymi datami i godziną.
> Niemniej jednak średnio to wygląda, gdy się patrzy na zakłócony ciąg logiczny wpisów.

**Comment by bacza** [comment]
Chodzi o stronę prezentacji znalezień użytkownika w serwisie Opencaching:
[https://opencaching.pl/my_logsFind.php](https://opencaching.pl/my_logsFind.php)

Wpisy sortowane są po dacie utworzenia logu, która w przypadku logowania z automatu może nie być wystarczająca. Może się zdarzyć, że aplikacja zdoła zalogować więcej niż jednego kesza w ciągu jednej sekundy i wtedy na stronie takie wpisy mogą być przemieszane (w obrębie tej sekundy).

Nie jest to problem GeoCentral, do poprawy jest sposób sortowania wpisów na tej stronie - po stronie serwera OC.

**Comment by bacza** [comment]
To samo dotyczy też strony:
[https://opencaching.pl/my_logs.php](https://opencaching.pl/my_logs.php)

**Comment by deg-pl** [comment]
@bacza W jaki sposób Twój program pobiera logi z serwera? Pobiera stronę /my_logsFind.php i ją analizuje, czy wykorzystując OKAPI? Bo jeśli zdrapuje dane ze strony, to robi to zdecydowanie źle. Logi (i inne dane) powinny być pobierane przez OKAPI https://opencaching.pl/okapi/introduction.html

**Comment by bacza** [comment]
@deg-pl nie pobiera, a wysyła ;)
Tak, przez OKAPI.

**Comment by bacza** [comment]
Poprawka wrzucona do repo: https://github.com/opencaching/opencaching-pl/pull/1656
